name: Extract URL and Version

on:
  issues:
    types: [opened]

jobs:
  extract:
    runs-on: ubuntu-latest
    steps:
      - name: Extract URL and Version
        id: extract
        run: |
          ISSUE_BODY="${{ github.event.issue.body }}"
          URL=$(echo "$ISSUE_BODY" | grep -oP 'https://\S+')
          VERSION=$(echo "$ISSUE_BODY" | grep -oP 'Version:\s*\K\S+')
          echo "$URL"
          echo "$VERSION"

  use-extracted:
    needs: extract
    runs-on: ubuntu-latest
    steps:
      - name: Print Extracted Values
        run: |
          echo "URL: ${{ steps.extract.outputs.url }}"
          echo "Version: ${{ steps.extract.outputs.version }}"
